export const ShopActionTypes = {
  ASYNC_SHOP_REQUEST_START: '[SHOP] ASYNC_SHOP_REQUEST_START',
  ASYNC_SHOP_REQUEST_SUCCESS: '[SHOP] ASYNC_SHOP_REQUEST_SUCCESS',
  ASYNC_SINGLE_PRODUCT_SHOP_REQUEST_SUCCESS: '[SHOP] ASYNC_SINGLE_PRODUCT_SHOP_REQUEST_SUCCESS',
  ASYNC_SHOP_REQUEST_FAILURE: '[SHOP] ASYNC_SHOP_REQUEST_FAILURE',
  SET_PRODUCTS_FILTERS: '[SHOP] SET_PRODUCTS_FILTERS',
  CLEAR_PRODUCTS_FILTERS: '[SHOP] CLEAR_PRODUCTS_FILTERS',
};
