export const ShopActionTypes = {
  FETCH_SHOP_PRODUCTS_START: '[SHOP] FETCH_SHOP_PRODUCTS_START',
  FETCH_SHOP_PRODUCTS_SUCCESS: '[SHOP] FETCH_SHOP_PRODUCTS_SUCCESS',
  FETCH_SHOP_PRODUCTS_FAILURE: '[SHOP] FETCH_SHOP_PRODUCTS_FAILURE',
  SET_PRODUCTS_FILTERS: '[SHOP] SET_PRODUCTS_FILTERS',
  CLEAR_PRODUCTS_FILTERS: '[SHOP] CLEAR_PRODUCTS_FILTERS',
};
