export const CartActionTypes = {
  CLOSE_CART_DROPDOWN: '[CART] CLOSE_CART_DROPDOWN',
  TOGGLE_CART_DROPDOWN: '[CART] TOGGLE_CART_DROPDOWN',
  CLEAR_WHOLE_CART: '[CART] CLEAR_WHOLE_CART',
  ASYNC_CART_REQUEST_START: '[CART] ASYNC_CART_REQUEST_START',
  ASYNC_CART_REQUEST_SUCCESS: '[CART] ASYNC_CART_REQUEST_SUCCESS',
  ASYNC_CART_REQUEST_FAILURE: '[CART] ASYNC_CART_REQUEST_FAILURE',
};
