export const CartActionTypes = {
  CLOSE_CART_DROPDOWN: '[CART] CLOSE_CART_DROPDOWN',
  TOGGLE_CART_DROPDOWN: '[CART] TOGGLE_CART_DROPDOWN',
  ADD_CART_ITEM: '[CART] ADD_CART_ITEM',
  REMOVE_CART_ITEM: '[CART] REMOVE_CART_ITEM',
  CLEAR_CART_ITEM: '[CART] CLEAR_CART_ITEM',
};
