export const PaymentActionTypes = {
  SET_SUCCESS_MESSAGE: '[PAYMENT] SET_SUCCESS_MESSAGE',
  CLEAR_MESSAGE: '[PAYMENT] CLEAR_MESSAGE',
  OPEN_PAYMENT_MODAL: '[PAYMENT] OPEN_PAYMENT_MODAL',
  CLOSE_PAYMENT_MODAL: '[PAYMENT] CLOSE_PAYMENT_MODAL',
  ASYNC_PAYMENT_REQUEST_START: '[PAYMENT] ASYNC_PAYMENT_REQUEST_START',
  ASYNC_PAYMENT_REQUEST_SUCCESS: '[PAYMENT] ASYNC_PAYMENT_REQUEST_SUCCESS',
  ASYNC_PAYMENT_REQUEST_FAILURE: '[PAYMENT] ASYNC_PAYMENT_REQUEST_FAILURE',
};
