export const UserActionTypes = {
  SET_SUCCESS_MESSAGE: '[USER] SET_SUCCESS_MESSAGE',
  CLEAR_MESSAGE: '[USER] CLEAR_MESSAGE',
  CLOSE_USER_DROPDOWN: '[USER] CLOSE_USER_DROPDOWN',
  TOGGLE_USER_DROPDOWN: '[USER] TOGGLE_USER_DROPDOWN',
  OPEN_USER_MODAL: '[USER] OPEN_USER_MODAL',
  CLOSE_USER_MODAL: '[USER] CLOSE_USER_MODAL',
  ASYNC_USER_REQUEST_START: '[USER] ASYNC_USER_REQUEST_START',
  ASYNC_USER_REQUEST_SUCCESS: '[USER] ASYNC_USER_REQUEST_SUCCESS',
  ASYNC_USER_REQUEST_FAILURE: '[USER] ASYNC_USER_REQUEST_FAILURE',
};
